sonar.projectKey=andreslopca_pet-insurance-devops
sonar.organization=andreslopca
sonar.sources=src
sonar.exclusions=**/*.spec.ts, **/node_modules/**, **/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info